In [24]:
import numpy as np
import pickle
import pandas as pd

In [25]:
# Load Model
filename = 'model.pkl'
loaded_model = pickle.load(open(filename,'rb'))

In [26]:
# Load Model
filename = 'model_transformer.pkl'
model_transfomer = pickle.load(open(filename,'rb'))
model_transfomer

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehot', OneHotEncoder(drop='first'),
                                 ['housing', 'loan', 'contact', 'month',
                                  'poutcome'])])

In [27]:
loaded_model

GradientBoostingClassifier(random_state=0)

In [28]:
# Create Observation
new_cust = pd.DataFrame({
    'age' : [32],
    'balance' : [200000],
    'housing' : ['no'],
    'loan' : ['no'],
    'contact' : ['cellular'],
    'month': ['jul'],
    'campaign' : [1],
    'pdays':[2],
    'poutcome':['success']}
)
new_cust

age  balance housing loan   contact month  campaign  pdays poutcome
0   32   200000      no   no  cellular   jul         1      2  success

In [29]:
loaded_model.predict(model_transfomer.transform(new_cust))

array([1])

In [43]:
df = pd.read_csv('data_test.csv')
df_transform = model_transfomer.transform(df)
df_transform[0]

array([ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  1.000e+00,  6.400e+01,  2.139e+03,
        2.000e+00, -1.000e+00])

In [31]:
y_pred = loaded_model.predict(df_transform)
y_pred

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [32]:
df['predict'] = np.where(y_pred == 1, 'deposit', 'not deposit')
df

age          job  balance housing loan    contact month  campaign  pdays  \
0    64      retired     2139      no   no   cellular   oct         2     -1   
1    31      student      307      no   no   cellular   nov         2     -1   
2    25   management      219      no   no   cellular   aug         1     96   
3    29  blue-collar      -20     yes   no    unknown   may         2     -1   
4    53       admin.      109      no   no  telephone   jun         1     -1   
..  ...          ...      ...     ...  ...        ...   ...       ...    ...   
95   58   technician     3399      no   no   cellular   may         1     97   
96   33     services     5034     yes   no    unknown   may         3     -1   
97   72      retired      951      no  yes   cellular   mar         3    339   
98   47   management      600      no   no   cellular   aug        15     -1   
99   35  blue-collar      159     yes  yes   cellular   may         1     -1   

   poutcome      predict  
0   unknown      deposit  
1   unknown  not deposit  
2   success      deposit  
3   unknown  not deposit  
4   unknown      deposit  
..      ...          ...  
95    other      deposit  
96  unknown  not deposit  
97  failure      deposit  
98  unknown  not deposit  
99  unknown  not deposit  

[100 rows x 11 columns]

In [33]:
np.__version__

'1.24.0'

In [34]:
pd.__version__

'2.1.4'